version: '3.8'

services:
  hide_japanese:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: hide_japanese
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, compute]
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=all
      - CUDA_HOME=/usr/local/cuda
      - PATH=/usr/local/cuda/bin:${PATH}
      - LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/lib:${LD_LIBRARY_PATH}