# .devcontainer/docker-compose.yml

services:
  hide_japanese:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: hide_japanese
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # ports:
    #   - "7861:7860" # Gradio interface
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=all