version: '3.8'

services:
  hide_japanese:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: hide_japanese
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8000:8000"
    volumes:
      - ../log:/workspace/log
      # - ../../hide_japanese_with_bert:/workspace/
    env_file:
      - ../.env