name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  # Cancels any currently running jobs if a new one is triggered

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install `uv`
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          export PATH="$HOME/.local/bin:$PATH"

      - name: Install dependencies
        run: uv sync  # Installs dependencies from pyproject.toml

      - name: Run Ruff Linter
        run: uv run ruff check .

      - name: Check Ruff Formatting
        run: uv run ruff format --check .  # Checks formatting without modifying code

  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.10'

  #     - name: Install `uv`
  #       run: |
  #         curl -LsSf https://astral.sh/uv/install.sh | sh
  #         export PATH="$HOME/.local/bin:$PATH"

  #     - name: Install dependencies
  #       run: uv sync  # Installs dependencies from pyproject.toml

  #     - name: Run Tests
  #       run: uv run pytest
